# https://codeclimate.com/
engines:
    phpcodesniffer:
        enabled: true
        config:
            file_extensions: php
            standard: PSR1
ratings:
    paths:
        - src/**
        - tests/**
exlude_paths:
    - bin
    - lib
    - var
